# Generated by Django 3.0.4 on 2020-10-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=20, verbose_name='region name')),
                ('existing_population', models.IntegerField(verbose_name='existing population')),
                ('current_personal', models.IntegerField(verbose_name='current personal')),
                ('required_personal', models.IntegerField(verbose_name='required personal')),
                ('generated_costs', models.FloatField(verbose_name='generated costs')),
                ('deads', models.IntegerField(verbose_name='deads')),
                ('qualification', models.IntegerField(verbose_name='qualification')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
    ]
