# Generated by Django 3.0.4 on 2020-09-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('poblacion', models.IntegerField()),
                ('estaciones_actuales', models.IntegerField()),
                ('personal_requerido', models.IntegerField()),
                ('costos', models.FloatField()),
                ('muertes', models.IntegerField()),
                ('cualificacion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
    ]
