# Generated by Django 3.0.4 on 2020-10-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='cualificacion',
            new_name='current_personal',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='estaciones_actuales',
            new_name='deads',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='muertes',
            new_name='existing_population',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='costos',
            new_name='generated_costs',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='personal_requerido',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region_name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='poblacion',
            new_name='required_personal',
        ),
    ]
